### ISSUE TITLE
Demo app crash

### ISSUE THREAD

**Issue by Naveengskumar** [maddevsio/mad-location-manager#120]
java.lang.NoClassDefFoundError: mad.location.manager.lib.locationProviders.GPSLocationProvider$3
        at mad.location.manager.lib.locationProviders.GPSLocationProvider.<init>(GPSLocationProvider.java:76)
        at mad.location.manager.lib.Services.KalmanLocationService.onCreate(KalmanLocationService.java:389)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2895)
        at android.app.ActivityThread.-wrap4(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by Lezh1k** [comment]
Probably [new version](https://github.com/maddevsio/mad-location-manager-lib) will work better.
