### ISSUE TITLE
Need help for starting demo app

### ISSUE THREAD

**Issue by Survivor2302** [maddevsio/mad-location-manager#124]
When i start the demo application i got the error :
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.lezh1k.sensordatacollector, PID: 20579
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.lezh1k.sensordatacollector/com.example.lezh1k.sensordatacollector.MainActivity}: java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at

**Comment by Lezh1k** [comment]
@Survivor2302  Hello. Could you update library and try again + provide full exception log?

**Comment by daniel-costaa** [comment]
@Survivor2302 I had the same problem, but fixed it by giving [this](https://stackoverflow.com/questions/62692649/getnetworktype-in-android-11) permission.
